# Generated by Django 3.1 on 2020-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
                ('location', models.CharField(choices=[('CHI', 'Chicago'), ('ATL', 'Atlanta')], max_length=3)),
            ],
        ),
    ]
