# Generated by Django 3.1 on 2020-08-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermgr', '0002_auto_20200814_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='location',
            field=models.CharField(choices=[(0, 'Chicago'), ('ATL', 'Atlanta'), ('NYC', 'New York (NJ)'), ('DAL', 'Dallas'), ('LAX', 'Los Angeles'), ('MIA', 'Miami'), ('SEA', 'Seattle')], max_length=3),
        ),
    ]
