# Generated by Django 3.1 on 2020-08-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servermgr', '0005_auto_20200814_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='plan',
            field=models.CharField(choices=[(400, '1G RAM 25GB 1TB BW')], default=400, max_length=40),
        ),
        migrations.AlterField(
            model_name='server',
            name='operatingsystem',
            field=models.CharField(choices=[(167, 'CentOS7')], default=167, max_length=10),
        ),
    ]
